# Uncomment the next line to define a global platform for your project
 platform :macos, '14.3'

target 'rtc_macos' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for rtc_macos
  pod 'Socket.IO-Client-Swift', '~> 16.1.1'
  pod 'PureLayout'
#  pod 'WebRTC-lib', '~> 134.0.0'

end
